---
- hosts: all
  tasks:
   - name: install redhat-access-insights
     yum:
      name:  insights-client
 
   - name: insights registration 
     command: insights-client --register --display-name "{{ ansible_hostname }}"

