- hosts: all
  tasks:
      - name: Register and subscribe to a specific pool by ID.
        redhat_subscription:
          state: absent

      - name: insights unregistration 
        command: insights-client --unregister
