- hosts: all
  tasks:
      - name: Register and subscribe to a specific pool by ID.
        redhat_subscription:
          state: absent

      - name: insights registration 
        command: insights-client --register --display-name "{{ ansible_hostname }}"
