---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
#  become: true
  tasks:
        - name: Register and subscribe to a specific pool by ID.
          redhat_subscription:
            state: present
            username: "{{ rh_username }}"
            password: "{{ rh_password }}"
            auto_attach: true
